### ISSUE TITLE
Include ROS files fails

### ISSUE THREAD

**Issue by AlexisFetet** [CentraleNantesRobotics/baxter_common_ros2#1]
During ecn VM installation from scratch, compiling ros2 workspace fails due to package baxter_bridge.

```
--- stderr: baxter_bridge                             
In file included from /opt/local_ws/ros2/src/baxter_common_ros2/baxter_bridge/src/baxter_bridge.cpp:1:
/opt/local_ws/ros2/src/baxter_common_ros2/baxter_bridge/include/baxter_bridge/solve_ik.h:7:10: fatal error: baxter_core_msgs/SolvePositionIK.h: No such file or directory
    7 | #include <baxter_core_msgs/SolvePositionIK.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/baxter_bridge.dir/build.make:63: CMakeFiles/baxter_bridge.dir/src/baxter_bridge.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/baxter_bridge.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< baxter_bridge [5.46s, exited with code 2]
```

ROS1 .h files are apparently not found at compile time. [This commit ](https://github.com/CentraleNantesRobotics/baxter_common_ros2/commit/f771274c9c9c6639c35f07dc785e0c573ced3b42) changes the place to look for for the packages, however this directory does not exist at installation time on the VM:
```
ecn@ecn-focal:/opt$ ls
coppeliaSim  duels  local_ws  pycharm  ros  VBoxGuestAdditions-6.1.34
```
Changing this value did not fix the issue.
When looking at `/opt/local_ws/ros1/install/include/baxter_core_msgs` : 
```
[ROS2] ecn@ecn-focal:/opt/local_ws/ros1/install/include/baxter_core_msgs$ ls
AnalogIOState.h        AssemblyStates.h  CloseCameraRequest.h       DigitalIOState.h        EndEffectorProperties.h  HeadPanCommand.h  ListCamerasRequest.h   OpenCamera.h              SEAJointState.h            URDFConfiguration.h
AnalogIOStates.h       CameraControl.h   CloseCameraResponse.h      DigitalIOStates.h       EndEffectorState.h       HeadState.h       ListCamerasResponse.h  OpenCameraRequest.h       SolvePositionIK.h
AnalogOutputCommand.h  CameraSettings.h  CollisionAvoidanceState.h  DigitalOutputCommand.h  EndpointState.h          JointCommand.h    NavigatorState.h       OpenCameraResponse.h      SolvePositionIKRequest.h
AssemblyState.h        CloseCamera.h     CollisionDetectionState.h  EndEffectorCommand.h    EndpointStates.h         ListCameras.h     NavigatorStates.h      RobustControllerStatus.h  SolvePositionIKResponse.h
```
The file is actually present but not detected by the compiler. It looks like the directory is not included properly since I cannot include any file in this directory.

**Comment by AlexisFetet** [comment]
Here is the output during the installation
```
 [ecn]     catkin build  --continue-on-failure
 [ecn]      ↪ Compiling ROS 1 auxiliary workspace @ /opt/local_ws/ros1 ✓
 [ecn]     bash -c -i "source /opt/ros/foxy/setup.bash && IGNITION_VERSION=fortress colcon build --symlink-install --continue-on-error"
<class 'subprocess.CalledProcessError'> Command '['bash', '-c', '-i', 'source /opt/ros/foxy/setup.bash && IGNITION_VERSION=fortress colcon build --symlink-install --continue-on-error']' returned non-zero exit status 2. <traceback object at 0x7f01845ad140>
Traceback (most recent call last):liary workspace @ /opt/local_ws/ros2 -
  File "./update.py", line 858, in perform
    perform_update()
  File "./update.py", line 715, in perform_update
    run([f'bash -c -i "source /opt/ros/{ros2}/setup.bash && IGNITION_VERSION=fortress colcon build --symlink-install --continue-on-error"',f'Compiling ROS 2 auxiliary workspace @ {Depend.folders[Source.GIT_ROS2]}'], cwd=Depend.folders[Source.GIT_ROS2], show=True)
  File "./update.py", line 108, in run
    out = check_output(shlex.split(cmd), stderr=PIPE, cwd=cwd).decode('utf-8').splitlines()
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    else:
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    # We don't call process.wait() as .__exit__ does that for us.
subprocess.CalledProcessError: Command '['bash', '-c', '-i', 'source /opt/ros/foxy/setup.bash && IGNITION_VERSION=fortress colcon build --symlink-install --continue-on-error']' returned non-zero exit status 2.
```

**Comment by oKermorgant** [comment]
Indeed I am preparing a Ubuntu 22.04/Humble VM and thought `/opt/local_ws` was not a good name for ECN-specific workspace. It was renamed to `/opt/ecn`, hence the new default path that is not backward-compatible.

Changing `CMakeLists.txt` afterwards does not work as this path is cached. The best thing would be to have CMake look for the ROS 1 `baxter_core_msgs` package but it really can be anywhere.

For the VM you can either:
- compile `baxter_bridge` with the correct path: `colcon build --symlink-install --packages-select baxter_bridge --cmake-args -DROS1_BAXTER_WS:=/opt/ecn/ros1`
- or do a sym link `sudo ln -s /opt/local_ws /opt/ecn` that will do the trick.

**Comment by oKermorgant** [comment]
I have updated `baxter_bridge` to include custom ROS 1 messages. There is now no need to locate the ROS 1 packages.
